apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t9ouw91yu-python 
  janus-idp.io/tekton: t9ouw91yu-python
  backstage.io/kubernetes-id: t9ouw91yu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t9ouw91yu-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  